#!/bin/bash

# You probably need some of these e.g. gms(play service), vending(play store). 
# Edit this to your need.
packages=(
  "com.google.android.gms" #play service
  "com.huawei.android.totemweather"
  "com.netflix.partner.activation"
  "com.netflix.mediaclient"
  "com.nuance.swype.emui"
  "com.huawei.imedia.sws"
  "com.hicloud.android.clone"
  "com.android.sharedstoragebackup"
  "com.huawei.featurelayer.sharedfeature.map"
  "com.huawei.printservice"
  "com.huawei.android.internal.app"
  "om.huawei.android.totemweather"
  "com.huawei.android.wfdft"
  "com.android.imedia.syncplay"
  "com.huawei.featurelayer.featureframework"
  "com.huawei.ridemode"
  "com.huawei.android.hwupgradeguide"
  "com.huawei.parentcontrol"
  "com.huawei.vassistant"
  "com.huawei.phoneservice"
  "com.huawei.iaware"
  "com.huawei.hdiw"
  "com.huawei.geofence"
  "com.huawei.desktop.explorer"
  "com.huawei.contactscamcard"
  "com.huawei.bluetooth"
  "com.huawei.android.tips"
  "com.huawei.android.mirrorshare"
  "com.huawei.android.karaoke"
  "com.huawei.android.hsf"
  "com.huawei.android.chr"
  "com.huawei.appmarket"
  "com.hisi.mapcon"
  "com.baidu.input_huawei"
  "com.huawei.trustagent"
  "com.huawei.stylus.floatmenu"
  "com.iflytek.speechsuite"
  "com.google.android.googlequicksearchbox"
  "com.google.android.apps.docs.editors.docs"
  "com.google.android.apps.docs.editors.sheets"
  "com.google.android.apps.docs.editors.slides"
  "com.android.managedprovisioning"
  "com.android.mediacenter"
  "com.android.providers.partnerbookmarks"
  "com.android.voicedialer"
  "com.google.android.apps.books"
  "com.google.android.apps.cloudprint"
  "com.google.android.apps.currents"
  "com.google.android.apps.docs"
  "com.google.android.apps.fitness"
  "com.google.android.apps.mapps"
  "com.google.android.apps.photos"
  "com.google.android.apps.plus"
  "com.google.android.apps.restore"
  "com.google.android.apps.tachyon"
  "vStudio.Android.Camera360"
  "com.huawei.gameassistant"
  "com.android.backupconfirm"
  "com.google.android.backuptransport"
  "com.google.android.apps.restore"
  "com.google.android.feedback"
  "com.google.android.gm" #gmail
  "com.google.android.onetimeinitializer"
  "com.google.android.setupwizard"
  "com.google.android.syncadapters.calendar"
  "com.google.android.videos"
  "com.google.android.youtube"
  "com.google.android.measure"
  "com.huawei.android.remotecontroller"
  "com.huawei.search"
  "com.huawei.contactscamcard"
  "com.huawei.fido.uafclient"
  "com.huawei.hifolder"
  "com.huawei.himovie.overseas"
  "com.huawei.hwasm"
  "com.huawei.hwdetectrepair"
  "com.huawei.livewallpaper.paradise"
  "com.huawei.screenrecorder"
  "com.huawei.wallet"
  "com.huawei.watch.sync"
  "com.touchtype.swiftkey"
  "com.swiftkey.swiftkeyconfigurator"
  "com.google.android.ims"
  "com.google.android.gsf"
  "com.google.android.music"
  "com.google.android.overlay.gmsconfig"
  "com.google.android.printservice.recommendation"
  "com.google.android.gms.policy_sidecar_aps" #play service 
  "com.google.android.googlequicksearchbox" # google app
  "com.google.android.configupdater"
  "com.google.android.overlay.settingsProvider"
  "com.google.android.marvin.talkback"
  "com.google.android.apps.work.oobconfig"
  "com.google.android.apps.maps"
  "com.facebook.services"
  "com.facebook.system"
  "com.facebook.appmanager"
  "com.google.android.apps.messaging"
  "com.google.android.ext.services"
  "com.google.android.ext.shared"
  "com.google.android.syncadapters.contacts"
  "com.google.android.tts"
  "com.huawei.bd"
  "com.huawei.android.launcher"
  "com.huawei.hwid"
  "com.huawei.omacp" 
  "com.huawei.hicloud"
  "com.huawei.meetime"
  "com.android.vending" # play store
  "com.android.chrome"
  "com.google.android.partnersetup"
  "com.agoda.mobile.consumer"
  "com.facebook.katana"
  "com.facebook.orca"
  "com.booking"
)

# Remove packages from current user; not from system itself
for package in "${packages[@]}"; do
  echo "Removing $package..."
  adb uninstall --user 0 $package
done

# Clear package data
for package in "${packages[@]}"; do
  echo "Clearing data for $package..."
  adb shell pm clear $package
done
